name: Auto Commit Changes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa de hora em hora
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "mppt24-bot"
          git config --global user.email "mppt24-bot@users.noreply.github.com"

      - name: Verificar alterações
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Sem alterações para commit."
            exit 0
          fi
          git commit -m "Atualização automática"
          git push
